Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
  ### DB vm  ####
    config.vm.define "manual-deployment-server" do |server|
      server.vm.box = "geerlingguy/rockylinux8"
      server.vm.hostname = "md-server"
      server.vm.network "private_network", ip: "192.168.56.15"
      server.vm.provision "shell", path: "mysql_setup.sh"  
      server.vm.provision "shell", path: "webapp_setup.sh"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
      end
    end
end