apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot-container
          image: iatiqul/spark-lms:1.0
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: spring-boot
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 30080
  type: NodePort
